# Generated by Django 4.2.16 on 2024-11-05 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="cars/%Y/%m/%d"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("available", models.BooleanField(default=True)),
                ("created", models.DateField(auto_now_add=True)),
                ("updated", models.DateField(auto_now=True)),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=4
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="main.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarSpecifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("distance", models.IntegerField()),
                (
                    "engine_capacity",
                    models.DecimalField(decimal_places=2, max_digits=2),
                ),
                ("engine_power", models.IntegerField()),
                ("owners", models.IntegerField()),
                ("pts", models.CharField(max_length=12)),
                ("customs", models.BooleanField(default=True)),
                ("slug", models.SlugField()),
                (
                    "car_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carspecifications",
                        to="main.cars",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.AddIndex(
            model_name="cars",
            index=models.Index(
                fields=["id", "slug"], name="main_cars_id_bfcaef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cars",
            index=models.Index(
                fields=["name"], name="main_cars_name_434da3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cars",
            index=models.Index(
                fields=["-created"], name="main_cars_created_d5508e_idx"
            ),
        ),
    ]
