# Generated by Django 4.2.16 on 2024-11-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_carspecifications_type_engine"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cars",
            options={
                "ordering": ["name"],
                "verbose_name": "Машина",
                "verbose_name_plural": "Машины",
            },
        ),
        migrations.AlterModelOptions(
            name="carspecifications",
            options={
                "ordering": ["name"],
                "verbose_name": "Харрактреристика машины",
                "verbose_name_plural": "Харрактреристики машин",
            },
        ),
        migrations.AlterField(
            model_name="carspecifications",
            name="engine_capacity",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AddIndex(
            model_name="carspecifications",
            index=models.Index(
                fields=["name"], name="main_carspe_name_06ea78_idx"
            ),
        ),
    ]
